### ISSUE TITLE
destop verssion review 

### ISSUE THREAD

**Issue by techmoves** [katfogy/setup-and-mobile-first#16]
good job you did well on this project
![StandingOvationGIF](https://user-images.githubusercontent.com/110924992/230564368-e3ce12fd-dfac-4f81-926f-9a0397da3e5f.gif)

✔️ GOOD JOB

- [x] please kindly align your content on the about section yours is at center  kindly align then at the start on "the language part"
- [x] also align the drop down arrows to be same as figma design
- [x] In your form kindly change the color of the place holder for "write your message here"

**Comment by katfogy** [comment]
Thank you for your Recommendations, all effected
